<DownloadRow@MDCard>:
    grabacion_id: 0
    ruta_local: ""
    titulo: ""
    fecha: ""
    peso_txt: ""
    orientation: "horizontal"
    size_hint_y: None
    height: dp(64)
    padding: dp(10)
    spacing: dp(12)
    radius: [14, 14, 14, 14]
    theme_bg_color: "Custom"
    md_bg_color: 1, 1, 1, 1
    style: "elevated"
    ripple_behavior: True
    on_release: app.abrir_reproductor(self.grabacion_id, self.ruta_local)

    MDIcon:
        icon: "play-circle"
        theme_text_color: "Custom"
        text_color: 0.09, 0.16, 0.55, 1
        font_size: "30sp"

    BoxLayout:
        orientation: "vertical"
        MDLabel:
            text: root.titulo
            bold: True
            font_style: "Title"
            role: "small"

        MDLabel:
            text: root.fecha + "   •   " + root.peso_txt
            theme_text_color: "Secondary"
            font_style: "Body"
            role: "small"

    MDIcon:
        icon: "check-circle"
        theme_text_color: "Custom"
        text_color: 0.2, 0.7, 0.3, 1

<DownloadsTab>:
    name: "downloads_tab"
    md_bg_color: 1, 1, 1, 1

    BoxLayout:
        orientation: "vertical"
        padding: dp(16)
        spacing: dp(12)

        MDLabel:
            text: "Descargas"
            bold: True
            font_style: "Headline"
            role: "small"
            theme_text_color: "Custom"
            text_color: 0.09, 0.16, 0.55, 1
            size_hint_y: None
            height: dp(40)

        ScrollView:
            BoxLayout:
                id: contenedor
                orientation: "vertical"
                spacing: dp(14)
                size_hint_y: None
                height: self.minimum_height
